### ISSUE TITLE
Example files to run NucleoMap

### ISSUE THREAD

**Issue by EasyPiPi** [liu-bioinfo-lab/NucleoMap#1]
Hi Dr. Liu,

    I hope you are doing well! I recently read your NucleoMap paper and I'm very interested in using your tool to model and extract Nucleosome positioning information from microC data. I'm wondering if there is any test/toy dataset I can use to run your scripts? I have a few questions about the inputs and outputs. For example, 

    python nucleomap.py <read centers> <out dir> <PWM> <reference genome> 

    (1) What is <PWM>?
    
    (2) Is <read centers> the numpy array read_centers.npy output by infer_center.py?

    (3) Is <reference genome> ref_genome.fa or output.fa in the step using bedtools?    

    I'm imagining a test example will help me much better understand what kind of inputs and outputs I should expect. If that's not available, I should be able to test it using my own data under your guidance. 

    Look forward to your reply and thanks for reading my questions!

Best,
Yixin

**Comment by yuanhao96** [comment]
Hi Yixin,

Thanks for your suggestion! I am generating an example file with a Jupyter Notebook running the pipeline.

Best,
Yuanhao

**Comment by EasyPiPi** [comment]
Thanks Yuanhao, look forward to it!

**Comment by yuanhao96** [comment]
I have updated the scripts together with a tutorial.

Thanks,
Yuanhao
